name: Build & release wine
on:
  workflow_dispatch:
env:
  CC: "gcc-9"
  CXX: "g++-9"
  CROSSCC_X32: "i686-w64-mingw32-gcc"
  CROSSCXX_X32: "i686-w64-mingw32-g++"
  CROSSCC_X64: "x86_64-w64-mingw32-gcc"
  CROSSCXX_X64: "x86_64-w64-mingw32-g++"
  CFLAGS_X32: "-march=x86-64 -msse2 -mfpmath=sse -O2 -ftree-vectorize"
  CFLAGS_X64: "-march=x86-64 -msse3 -mfpmath=sse -O2 -ftree-vectorize"
  # CFLAGS_X64: "-O3 -pipe -march=x86-64-v2 -mpclmul -mavx"  # https://github.com/vinegarhq/wine-builds/blob/master/.github/workflows/wine.yml
  LDFLAGS: "-Wl,-O1,--sort-common,--as-needed"
  WINE_CONFIG: "--without-capi --without-coreaudio --without-gphoto --without-gssapi --without-inotify --without-krb5 --without-oss --without-pcap --without-pcsclite --without-sane --disable-winemenubuilder --disable-win16 --disable-tests --enable-archs=i386,x86_64"
  DEV_PKGS: "libavcodec-dev libcups2-dev libdbus-1-dev libffmpeg-nvenc-dev libffmpeg-ocaml-dev libfontconfig-dev libfreetype6-dev libgcrypt20-dev libgettextpo-dev libgnutls28-dev libgphoto2-dev libgstreamer-plugins-base1.0-dev libjxr-dev liblcms2-dev libopengl-dev libosmesa6-dev libpcsclite-dev libpulse-dev samba-dev libudev-dev libunwind-dev libusb-1.0-0-dev libv4l-dev libvulkan-dev libwayland-bin libwayland-dev waylandpp-dev libxcb-xkb-dev libxcomposite-dev libxcursor-dev libxi-dev libxpresent-dev libxrandr-dev"
  BUILD_PKGS: "bison flex g++-9 g++-mingw-w64 gcc-9 gcc-mingw-w64 gcc-multilib pkgconf"
  PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig"

jobs:
  build:
    # Ubuntu focal (20.04) fails to build 64-bit b/c libavcodec-dev does not include bsf.h.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wine-mirror/wine
          ref: wine-9.19
          fetch-depth: 1
      - name: wine-prep
        id: wine-prep
        run: |
          # Update environment.
          echo CROSSCFLAGS_X32=$CFLAGS_X32 >> "$GITHUB_ENV"
          echo CROSSCFLAGS_X64=$CFLAGS_X64 >> "$GITHUB_ENV"
          echo CROSSLDFLAGS=$LDFLAGS >> "$GITHUB_ENV"
          echo WINE64_DIR=$GITHUB_WORKSPACE/wine64 >> "$GITHUB_ENV"
          echo WINE32_TOOLS_DIR=$GITHUB_WORKSPACE/wine32-tools >> "$GITHUB_ENV"
          echo WINE32_DIR=$GITHUB_WORKSPACE/wine32 >> "$GITHUB_ENV"
          echo MAKEFLAGS="-j$(($(nproc) + 1))" >> "$GITHUB_ENV"
          # sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get --yes install $BUILD_PKGS $DEV_PKGS
      - name: set wine64 env
        # Can't use env: here b/c can't refer to existing env vars in their definitions.
        run: |
          echo "CROSSCC=$CROSSCC_X64" >> "$GITHUB_ENV"
          echo "CROSSCXX=$CROSSCXX_X64" >> "$GITHUB_ENV"
          echo "CFLAGS=$CFLAGS_X64" >> "$GITHUB_ENV"
          echo "CXXFLAGS=$CFLAGS_X64" >> "$GITHUB_ENV"
          echo "CROSSCFLAGS=$CROSSCFLAGS_X64" >> "$GITHUB_ENV"
          echo "CROSSCXXFLAGS=$CROSSCFLAGS_X64" >> "$GITHUB_ENV"
      - name: build wine64
        id: wine64
        run: |
          mkdir -p "$WINE64_DIR" && cd "$WINE64_DIR"
          $GITHUB_WORKSPACE/configure $WINE_CONFIG --enable-win64 --prefix=/wine-devel-amd64 --verbose
          make
      - name: set wine32-tools env
        run: |
          echo "CROSSCC=$CROSSCC_X32" >> "$GITHUB_ENV"
          echo "CROSSCXX=$CROSSCXX_X32" >> "$GITHUB_ENV"
          echo "CFLAGS=$CFLAGS_X32" >> "$GITHUB_ENV"
          echo "CXXFLAGS=$CFLAGS_X32" >> "$GITHUB_ENV"
          echo "CROSSCFLAGS=$CROSSCFLAGS_X32" >> "$GITHUB_ENV"
          echo "CROSSCXXFLAGS=$CROSSCFLAGS_X32" >> "$GITHUB_ENV"
      - name: build wine32-tools
        id: wine32-tools
        env:
          PKG_CONFIG_LIBDIR: /usr/lib/i386-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/i386-linux-gnu/pkgconfig
        run: |
          mkdir -p "$WINE32_TOOLS_DIR" && cd "$WINE32_TOOLS_DIR"
          $GITHUB_WORKSPACE/configure $WINE_CONFIG --prefix=/wine-devel-x86
          make
      - name: set wine32 env
        run: |
          echo "CROSSCC=$CROSSCC_X32" >> "$GITHUB_ENV"
          echo "CROSSCXX=$CROSSCXX_X32" >> "$GITHUB_ENV"
          echo "CFLAGS=$CFLAGS_X64" >> "$GITHUB_ENV"
          echo "CXXFLAGS=$CFLAGS_X64" >> "$GITHUB_ENV"
          echo "CROSSCFLAGS=$CROSSCFLAGS_X64" >> "$GITHUB_ENV"
          echo "CROSSCXXFLAGS=$CROSSCFLAGS_X64" >> "$GITHUB_ENV"
      - name: build wine32
        id: wine32
        env:
          PKG_CONFIG_LIBDIR: /usr/lib/i386-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/i386-linux-gnu/pkgconfig
        run: |
          mkdir -p "$WINE32_DIR" && cd "$WINE32_DIR"
          $GITHUB_WORKSPACE/configure $WINE_CONFIG --with-wine64="$WINE64_DIR" --with-wine-tools="$WINE32_TOOLS_DIR" --prefix=/wine-devel
          make
      - name: Upload logs
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: '**/*.log'
          retention-days: 2
      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: wine-devel-9.19-wow64
          path: wine-devel/*
